---
- name: Add validation key
  apt_key:
    keyring: "{{ repo_keyring }}"
    url: "{{ repo_url }}"
    id: "{{ repo_id }}"
    state: "{{ repo_state }}"
    validate_certs: yes
  register: result_key

- name: Add repository to source list
  apt_repository:
    filename: "{{ repo_filename }}"
    repo: "{{ repo }}"
    state: "{{ repo_state }}"
    mode: "{{ repo_mode | default('0644') }}"
    validate_certs: yes
  register: result_repo