---
- name: "Synchronization with exclude src to dest - {{ mode }}"
  when: ex
  synchronize:
    mode: "{{ mode }}"
    src: "{{ src }}"
    dest: "{{ dest }}"
    rsync_opts:
      - "--exclude={{ ex }}"  
  register: result_rsync

- name: "Synchronization src to dest - {{ mode }}"
  when: not ex
  synchronize:
    mode: "{{ mode }}"
    src: "{{ src }}"
    dest: "{{ dest }}"
  register: result_rsync2

- debug: var=result_rsync.stdout_lines
  when: ex
- debug: var=result_rsync2.stdout_lines
  when: not ex